### ISSUE TITLE
SEGV_MAPERR and graphical glitch with SW_WRITE_OFTEN flagged buffers

### ISSUE THREAD

**Issue by maurossi** [robherring/gbm_gralloc#22]
Hello,
This one is really tricky for my limited hobbyst knowledge, 

I'm opening in order to triage, as this is the last issue preventing the use of gbm_gralloc as default gralloc in android-x86 with Android R - NOTE: Android R requires hwbinder composer@2.1-service and gbm_gralloc needs to become the default gralloc

I'm opening a ticket for a problem happening only with gbm_gralloc and logged on r600 (AMD TURKS)
but it is happening also with radeonsi and nouveau.

As a comparison the problem does not happen with minigbm with the same GPUs and mesa version

```
0x76d2d8fe6ba0: 9328.00 KiB | 2006 (2048) x 1166 |    1 |        1 | 0x933 | android/com.android.internal.app.ResolverActivity#0
0x76d2d8fe8d10: 9328.00 KiB | 2006 (2048) x 1166 |    1 |        1 | 0x933 | android/com.android.internal.app.ResolverActivity#0
0x76d2d8fea250: 9328.00 KiB | 2006 (2048) x 1166 |    1 |        1 | 0x933 | android/com.android.internal.app.ResolverActivity#0
```

0x933 flags correspond to
`GRALLOC_USAGE_HW_COMPOSER | GRALLOC_USAGE_HW_TEXTURE | GRALLOC_USAGE_SW_WRITE_OFTEN | GRALLOC_USAGE_SW_READ_OFTEN`

Android R android-11.0.0_r17 mesa 21.0.1

![ResolverActivity_20210405-152214](https://user-images.githubusercontent.com/8344980/113611929-784fa380-964f-11eb-8d7c-9af75f2d14ca.png)

I'm adding logs in the attachments: `tombstone`, `addr2line`, `modetest` and `dumpsys SurfaceFlinger`

[logcat_gbm_gralloc_glitch.zip](https://github.com/robherring/gbm_gralloc/files/6259859/logcat_gbm_gralloc_glitch.zip)

[tombstone_00_gbm_gralloc_glitch.txt](https://github.com/robherring/gbm_gralloc/files/6259762/tombstone_00_gbm_gralloc_glitch.txt)

[addr2line_gbm_gralloc_glitch.txt](https://github.com/robherring/gbm_gralloc/files/6259772/addr2line_gbm_gralloc_glitch.txt)

[modetest_gbm_gralloc_glitch.txt](https://github.com/robherring/gbm_gralloc/files/6259789/modetest_gbm_gralloc_glitch.txt)

[dumpsys_gbm_gralloc_glitch.txt](https://github.com/robherring/gbm_gralloc/files/6259778/dumpsys_gbm_gralloc_glitch.txt)

Chicken Invaders 3 is also affected as explained below, there is a top pane that should show Ads

![Chicken_Invaders_3_20210405-173449](https://user-images.githubusercontent.com/8344980/113611861-61a94c80-964f-11eb-9d89-65867a353ba7.png)

**Comment by rsglobal** [comment]
Very likely this bug is caused by wrong FORMAT_MODIFIER imported by EGL API and not related to gbm_gralloc itself.
https://github.com/GloDroid/glodroid_forks/commit/512464b287b5411d8cd63ec653029219c1ec2741

**Comment by maurossi** [comment]
Just another info, Emil Velikov after having seen the apperarence of attached artifacts,
suggested to first check about stride errors, since there is no problem with i965 and iris I also suspected mesa implementation but I was never able to actually triage and pin-point the root cause


AMD Kaveri
![Aspire ES1-521-87V7 (AMD KAVERI)](https://user-images.githubusercontent.com/8344980/118405919-4bdd6d00-b67a-11eb-868a-43504740b5d4.png)



AMD Raven
![Athlon 200GE (AMD RAVEN)](https://user-images.githubusercontent.com/8344980/118405963-8515dd00-b67a-11eb-81d4-d67a226dec4b.png)

So you suggest that it is a problem in mesa happening with drivers r600, radeonsi and nouveau too,
because those drivers, which now support the modifiers, do not pass the modifiers info correctly throught egl/android?

But then why are i965, iris workung perfectly fine ?

Should I then open an issue in mesa?

**Comment by maurossi** [comment]
Hello @robherring @rsglobal 

Just a few questions, to assess if there are two actual problems here, because there are some artifacts due to failed allocation/import and some others seem due to stride or alignment of the imported/mmap-ed memory regions used by Skia to paint SW_WRITE* buffers

Q1) Is the stride in the libdrm gralloc handle to be stored with metric in pixels or bytes? If it is in bytes is it correct that gralloc_gbm_bo_create() in gralloc_gmb.cpp stores the stride in pixels?

```
buffer_handle_t gralloc_gbm_bo_create(struct gbm_device *gbm,
		int width, int height, int format, int usage, int *stride)
{
...
	/* in pixels */
	*stride = gralloc_handle(handle)->stride / gralloc_gbm_get_bpp(format);

	return handle;
}
```

Q2) minigbm is not affected by any of the artifacts. Does the stride require some kind of aligment in general and it is not implemented in gbm_gralloc? In case it is needed is there a general rule applicable for all drivers?

Q3) in minigbm drv.c, which is the generic part of the single drivers backends, drv_bo_map() uses memcpy(). Is it correct that  memcpy() is not required in mmap code paths in gbm_gralloc?

Q4) in minigbm gbm.c gbm_bo_map() an offset variable is used, is offset implementation required in gbm_gralloc too?

Thanks

**Comment by maurossi** [comment]
Hello @rsglobal and @evelikov 

I followed your advise to log with ALOGD the stride and I found the following happenings

```
11-15 00:12:00.851  3026  3026 D GRALLOC-GBM: create BO, size=2006x1166, stride=129905000 fmt=1, usage=14
11-15 00:12:00.851  3026  3026 D GRALLOC-GBM: gbm_bo_get_stride(bo), size=2006x1166, stride=8192 fmt=1, usage=14
11-15 00:12:00.851  3026  3026 D GRALLOC-GBM: buffer usage = 00000933
...
11-15 00:12:02.753  8673  8673 D GRALLOC-GBM: lock bo 0x78d097f01630, cnt=0, usage=30 stride=8192
11-15 00:12:02.756  8673  8673 D GRALLOC-GBM: mapped bo 0x78d097f01630 (0, 0)-(2006, 1166) at 0x78cfe6f10000 stride=8192
...
11-15 00:12:02.757  8673  8673 D GRALLOC-GBM: lock bo 0x78d097f01630, cnt=0, usage=33 stride=8192
11-15 00:12:02.760  8673  8673 D GRALLOC-GBM: mapped bo 0x78d097f01630 (1317, 814)-(5, 150) at 0x78cfe83aa000 stride=5376
```

In the last two lines mapped bo stride differs from the allocation stride visible in the lock bo logged line

Based on suggestion by Roman, I have tried to disable GBM_BO_USE_SCANOUT for sw usage, as Emil did in drm_gralloc nouveau backend where sw_indicator would fully disable scanout, but this workaround did not work I am still seeing the artifacts in the ResolverActivity windows of launcher3 as depicted in previous images in both Athlon 200GE Vega3 APU and in dGPU AMD TURKS HD76xx with dedicated VRAM

I wanted to check with @evelikov if besides trying to port [1] you may suggest another option

[1] https://chromium-review.googlesource.com/c/chromiumos/platform/minigbm/+/1232673

**Comment by evelikov** [comment]
Must admit - I didn't follow all the details in the thread, but porting the minigbm patch [1] to gbm_gralloc sounds like a good addition. HTH o/

**Comment by maurossi** [comment]
Hi Emil, the doubt I have about [1] is that the stride of mmap-ed bo may turn out to be the same as per allocated bo stride and the problem is that when bo lock happens with L, T offsets due to cropped region locking for CPU write, we may end up with same problem.
I believe the actual problem may be related to [2]

[2] https://github.com/robherring/gbm_gralloc/commit/640b8f16644d56ca53d1130e026c9c2098574bfe#diff-6f6fdb75f8a0ab48d08b9791f928af16b42257c10c82509337094f4dd4154894

**Comment by evelikov** [comment]
Knowing the correct L/T offset (considering varying stride et al) at mmap time might not be possible. So mapping the whole range makes sense.

**Comment by zhouziyang** [comment]
@maurossi  did you resolve your issues? I'm not encounter this issue on Android 11, but on Android 12 / 13. I can reproduce this issue always on AMD GPU (report on Intel GPU either). ~~seems related to `DimLayer` (such as Permission Grant Dialog)~~. this issue is gone if setup `virtio-gpu` rendering.

mesa 22.0.0 / libdrm-2.4.109

**Comment by maurossi** [comment]
Hello @zhouziyang

In android-x86 Android 9, 10, 11, 12 we still have the problem,  for Android 13 preview 2 /aosp master we have not yet achieved the build, but I'm sure the problem is there too.

Here are the attempts I made, which have failed to solve:

- attempt 1  was glodroid Roman patch for gbm_gralloc to import the correct modifiers, but it did not work

- attempt 2 was to align width to 64 pixels, i.e.256 bytes the usage GRALLOC_SW_{READ,WRITE}_OFTEN buffers, and it did not work with r600 parts nor with AMD GPU parts

- attempt 3 was to to move allocator to binderized, where allocation should happen in a single process as opposed to passthrough where it does not happen in a single process, this also failed. BTW in Android S it also failed when using gles renderer which is by definition single threaded.

One way to avoid the problem in ResolverActivity dialogues is to apply [1] as a Workaround, but it does not solve the problem for all Apps windows.

[1] https://github.com/boringdroid/platform_frameworks_base/commit/eda1dde45b35f40dd74b0ccfb0287de5680b846a

It's interesting if with Android 11 you do confirm that you have no such issue with Resolver Activity dialogues on AMD GPU and Intel iGPU, please I need to know what branches are you using for frameworks/base and other gfx stack related projects e.g. kernel. 
Please recheck because I see no clear reason motivating that Android 11 is not affected, because in my case it is affected as well on r600, AMD GPU (radeonsi), crocus, iris.

Another interesting fact is that i965 was never affected by the problem and iris/crocus are affected, that should ring a bell that the problem is most probably in mesa dri, where classic dri drivers were not affected and gallium dri targets for crocus, iris, nouveau, r600, radeonsi are all affected.

In case you work for Google, could you please help us to understand why and how the Workaround of minigbm [2] may also work for gbm_gralloc?

[2] https://chromium-review.googlesource.com/c/chromiumos/platform/minigbm/+/1232673

I never fully understood the actual problem, that's why we're still stuck with this only issue, otherwise gbm_gralloc would be perfect and with almost zero maintenances, as it has always been intended to be.

I other people agree like me, that this is indeed a mesa dri problem, please confirm and we will continue the thread in a mesa issue

**Comment by zhouziyang** [comment]
@maurossi  thanks for your detailed info. I just tested on `radeonsi` (WX5100 / WX9100) platforms. I'm not encounter any rendering problems on Android 11 (arm64 / x86_64, ubuntu generic kernel 5.4 / 5.8 / 5.11 / 5.13...).
for code branches, please check https://github.com/remote-android/platform_manifests.
I' not work for Google currently, and I will look into the commit in minigbm you mentioned.

**Comment by zhouziyang** [comment]
as a workaround, just enable hardwareAccelerated (not sure why AOSP disable this in Android 12 / 13)
```
diff --git a/PermissionController/AndroidManifest.xml b/PermissionController/AndroidManifest.xml
index a6fee5833..144827872 100644
--- a/PermissionController/AndroidManifest.xml
+++ b/PermissionController/AndroidManifest.xml
@@ -111,7 +111,7 @@
                 android:theme="@style/GrantPermissions.FilterTouches"
                 android:visibleToInstantApps="true"
                 android:inheritShowWhenLocked="true"
-                android:hardwareAccelerated="false">
+                android:hardwareAccelerated="true">
             <intent-filter android:priority="1">
                 <action android:name="android.content.pm.action.REQUEST_PERMISSIONS" />
                 <category android:name="android.intent.category.DEFAULT" />
```

**Comment by maurossi** [comment]
Thanks @zhouziyang

A couple of questions, since you are a few steps ahead, is the hardwareAccelated="true" solving the problem also for Apps using Skia/SW rendering? Is this method applicable also to Android 11 and is it more effective than  [1] ?

[1] https://github.com/boringdroid/platform_frameworks_base/commit/eda1dde45b35f40dd74b0ccfb0287de5680b846a

Regarding redroid 11.0.0, in case you have not set hardwareAccelated="true", since you don't see the problem,
could it be that for you AMD GPU parts  WX5100 / WX9100 the buffers are always allocated on GPU VRAM memory and may that may be avoiding the issue for your parts?

Are you using [hwcomposer.drm + gralloc.gbm] or [no hwc and gralloc.gbm + drm_framebuffer] ?
In my case I have the ResolverActivity artifacts with both the HALs combinations.

 [hwcomposer.drm_minigbm + gralloc.minigbm] and [ no hwc and gralloc.minigbm + drm_framebuffer] are not affected

**Comment by zhouziyang** [comment]
@maurossi  I confirmed all these issues (SW / Skia rendering issue) exists in `gbm_gralloc`. And I think it's due to partial locking just like logs you mentioned above.

`hardwareAccelated="true"` is same effective as changing in Java code directly. But I prefer to change in `AndroidManifest.xml` / `some_themes.xml` instead of Java code (may save some compilation time).

`redroid` is a headless solution (not show on physical display), and not depend on `drm_framebuffer` / `hwcomposer.drm_minigbm` etc. I chose to use `gbm_gralloc` because it's easy to support different GPUs...

**Comment by maurossi** [comment]
> I chose to use gbm_gralloc because it's easy to support different GPUs...

Me too

I have tried to build Android S (s-x86 iso) with android:hardwareAccelerated="true" in PermissionController/AndroidManifest.xml, but the launcher3 still has some glitch in ResolverActivity window and the text and controls to select Home app do not show up

I will try to apply also the attached patch in frameworks/base

[0001-ResolverActivity-use-hardware-rendering-for-Intent-R.zip](https://github.com/robherring/gbm_gralloc/files/8358634/0001-ResolverActivity-use-hardware-rendering-for-Intent-R.zip)

**Comment by a279437145** [comment]
I'm trying to run redroid12 on my raspberrypi (4b , 8G)  , with the help of zhouziyang , i now can run it with a smooth display whit scrcpy .  
![image](https://user-images.githubusercontent.com/75509566/195512191-5319db0a-9ccd-42f4-b0ec-12f5627fc5ae.png)
but when i try to take screenshots with `adb shell screencap -p /sdcard/screen.png` , I get corrupted results
![screen](https://user-images.githubusercontent.com/75509566/195512476-dbe0e423-2b74-4588-9d9e-7d46755a4b1d.png)

debug files from redroid (logcat , dumpsys ,etc included):
[tmp.w81kt72k33.tar.gz](https://github.com/robherring/gbm_gralloc/files/9771170/tmp.w81kt72k33.tar.gz)

I'm just a student and I know nothing about this , but I'm willing to provide information about this running on raspberrypi.

**Comment by maurossi** [comment]
Hello @a279437145  ,

My issues with "screen wide" artifacts on AMD Kaveri, Kabini, Raven were solved by commit https://github.com/robherring/gbm_gralloc/commit/2944928b1c38a82edea8b0b75ac221ef06ff5db6 submitted by aleasto 

I was about to close this issue https://github.com/robherring/gbm_gralloc/issues/22 but I'm waiting to see the outcome of this discussion. [edit] Issue https://github.com/robherring/gbm_gralloc/issues/22 has been already closed.

There is indeed another artifact problem happening with iris and nouveau gallium drivers, correlated to stride, where mouse cursor using buffers "not aligned 2 pow X" (which is also using SW R/W OFTEN buffers) is showing artifact, maybe this problem with mouse cursor is correlated to your problem too.

Just a wild guess, no guarantees, if you are already using the updated branch of gbm_gralloc would you like to give a try to this "Hack" https://pastebin.com/raw/hrEGij38 which apparently avoids my artifacts problem on isis and nouveau?

Then we will see if the problem is completely defined and identified and if we may close this issue and how to treat my other artifact issue and yours.

**Comment by a279437145** [comment]
thank you 
I'm not running with intel gpu or nvidia gpu , so I'm not using iris or nouveau .
but however , i'll give it try

**Comment by a279437145** [comment]
Hi  @maurossi ,
Maybe a stupid question : After i synced code with 
```bash
./repo init -u https://github.com/remote-android/platform_manifests.git -b redroid-12.0.0 --depth=1
./repo sync -c
```
I didn't know where to apply the patch , the only `gralloc_gbm.cpp` I found was `device/linaro/dragonboard/gralloc/gralloc_gbm.cpp`
Is this the one to be changed?

Sorry for disturbing.

**Comment by zhouziyang** [comment]
@a279437145  graphics related blobs are prebuilt (`mesa3d`, `llvm`, `gralloc.gbm` etc.) in `redroid`.  I can provide you this patched `gralloc.gbm` if needed. And please move redroid discussion in [redroid-doc](https://github.com/remote-android/redroid-doc).

**Comment by maurossi** [comment]
>device/linaro/dragonboard/gralloc/gralloc_gbm.cpp
>Is this the one to be changed?

Correct

**Comment by a279437145** [comment]
thanks everyone , i tried that but i still got corrupted screenshots like before .
